name: OCaml (forks)

on: [push]

jobs:
  # Cancels previous runs of jobs in this file
  cancel:
    if: github.repository == 'ThomArr/Chess'
    name: "Cancel Previous Runs (CI)"
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Install dune-format
        run: opam install ocamlformat

      - name: Format
        run: opam exec -- dune build @fmt --auto-promote
